name: nova_delivery
description: نوفا ديليفري - منصة توصيل عربية احترافية.
publish_to: "none"
version: 2.0.0+2
environment:
  sdk: ">=3.10.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.15.4
  flutter_map: ^8.3.2
  geolocator: ^14.1.1
  image_picker: ^1.2.3
  http: ^1.5.0
  latlong2: ^0.10.1
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/nova_rider.webp

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/nova_rider.webp
  min_sdk_android: 21
